version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "22:22"
    volumes:
      - ./jenkins_home:/var/jenkins_home   # Creates `jenkins_home` directory automatically
    networks:
      deploy:
        ipv4_address: 192.168.100.10

  ansible:
    image: ansible/ansible:ubuntu1404                # Use an official Ansible image
    container_name: ansible-agent
    volumes:
      - ./playbooks:/playbooks             # Mounts `playbooks/` folder to `/playbooks` in the container
    networks:
      deploy:
        ipv4_address: 192.168.100.20

  docker:
    build: ./docker
    container_name: docker-agent
    privileged: true
    networks:
      deploy:
        ipv4_address: 192.168.100.30

networks:
  deploy:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
