services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   
    networks:
      deploy:
        ipv4_address: 192.168.100.10

  ansible:
    build: ./ansible               
    container_name: ansible-agent
    volumes:
      - ./playbooks:/playbooks
    ports:
      - "2000:22"            
    networks:
      deploy:
        ipv4_address: 192.168.100.20
    command: >
      sh -c "sleep 59 && java -jar /playbooks/agent.jar
      -url http://<jenkins-url/VM url>:8080/
      -secret <secret>
      -name ansible
      -workDir /home/jenkins"

  docker:
    build: ./docker
    container_name: docker-agent
    privileged: true
    ports:
      - "2001:22"
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dock:/dock
    networks:
      deploy:
        ipv4_address: 192.168.100.30
    command: >
      sh -c "sleep 59 && java -jar /dock/agent.jar
      -url http://<jenkins-url/VM url>:8080/
      -secret <secret>
      -name docker
      -workDir /home/jenkins"
  
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    privileged: true
    environment:
      NGROK_AUTHTOKEN: "<token>"  # Replace with your ngrok auth token
    command: "http 192.168.100.10:8080 --log=stdout"
    networks:
      deploy:
        ipv4_address: 192.168.100.40
    depends_on:
      - jenkins

networks:
  deploy:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
