version: '3.8'

services:
  jenkins:
    build: ./jenkins
    container_name: jenkins-master
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home   
    networks:
      deploy:
        ipv4_address: 192.168.100.10

  ansible:
    build: ./ansible               
    container_name: ansible-agent
    volumes:
      - ./playbooks:/playbooks
    ports:
      - "2000:22"            
    networks:
      deploy:
        ipv4_address: 192.168.100.20

  docker:
    build: ./docker
    container_name: docker-agent
    privileged: true
    ports:
      - "2001:22"
    networks:
      deploy:
        ipv4_address: 192.168.100.30

networks:
  deploy:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24