version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home   
    networks:
      deploy:
        ipv4_address: 192.168.100.10

  ansible:
    build: ./ansible               
    container_name: ansible-agent
    volumes:
      - ./playbooks:/playbooks
    ports:
      - "2000:22"            
    networks:
      deploy:
        ipv4_address: 192.168.100.20

  docker:
    build: ./docker
    container_name: docker-agent
    privileged: true
    ports:
      - "2001:22"
    networks:
      deploy:
        ipv4_address: 192.168.100.30
  
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    privileged: true
    environment:
      NGROK_AUTHTOKEN: "2o4MJoA2TCC1ZOlCe2Q7K4V8Bj6_VdkZK6GVBiTF3RfLLyEA"  # Replace with your ngrok auth token
    command: >
      http 192.168.100.10:8080 --log=stdout | grep --line-buffered 'started tunnel'
    networks:
      deploy:
        ipv4_address: 192.168.100.40
    depends_on:
      - jenkins

networks:
  deploy:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24